<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="0" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-11-15T10:29:46 IST" name="Default suite" finished-at="2023-11-15T10:30:15 IST" duration-ms="28886">
    <groups>
    </groups>
    <test started-at="2023-11-15T10:29:46 IST" name="Default test" finished-at="2023-11-15T10:30:15 IST" duration-ms="28886">
      <class name="TestCase_Repo.S1">
        <test-method is-config="true" signature="dbconnection()[pri:0, instance:TestCase_Repo.S1@1283bb96]" started-at="2023-11-15T10:29:45 IST" name="dbconnection" finished-at="2023-11-15T10:29:46 IST" duration-ms="1355" status="FAIL">
          <exception class="java.sql.SQLSyntaxErrorException">
            <message>
              <![CDATA[Unknown database 'asta']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLSyntaxErrorException: Unknown database 'asta'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
at generic_utility.DataBaseUtility.establishConnection(DataBaseUtility.java:20)
at generic_utility.BaseClass.dbconnection(BaseClass.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLSyntaxErrorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- dbconnection -->
        <test-method is-config="true" signature="launchingBrowser()[pri:0, instance:TestCase_Repo.S1@1283bb96]" started-at="2023-11-15T10:29:47 IST" name="launchingBrowser" finished-at="2023-11-15T10:30:00 IST" duration-ms="13807" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchingBrowser -->
        <test-method is-config="true" signature="loginOperation()[pri:0, instance:TestCase_Repo.S1@1283bb96]" started-at="2023-11-15T10:30:00 IST" name="loginOperation" finished-at="2023-11-15T10:30:06 IST" duration-ms="5580" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginOperation -->
        <test-method signature="createorg()[pri:0, instance:TestCase_Repo.S1@1283bb96]" started-at="2023-11-15T10:30:06 IST" name="createorg" finished-at="2023-11-15T10:30:06 IST" duration-ms="0" status="SKIP">
          <exception class="java.sql.SQLSyntaxErrorException">
            <message>
              <![CDATA[Unknown database 'asta']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.sql.SQLSyntaxErrorException: Unknown database 'asta'
at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:829)
at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:449)
at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:242)
at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
at generic_utility.DataBaseUtility.establishConnection(DataBaseUtility.java:20)
at generic_utility.BaseClass.dbconnection(BaseClass.java:23)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:317)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.sql.SQLSyntaxErrorException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createorg -->
        <test-method is-config="true" signature="logoutOperation()[pri:0, instance:TestCase_Repo.S1@1283bb96]" started-at="2023-11-15T10:30:06 IST" name="logoutOperation" finished-at="2023-11-15T10:30:15 IST" duration-ms="9184" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutOperation -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:TestCase_Repo.S1@1283bb96]" started-at="2023-11-15T10:30:15 IST" name="closeBrowser" finished-at="2023-11-15T10:30:15 IST" duration-ms="232" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="closedbconnection()[pri:0, instance:TestCase_Repo.S1@1283bb96]" started-at="2023-11-15T10:30:15 IST" name="closedbconnection" finished-at="1970-01-01T05:30:00 IST" duration-ms="-1700024415952" status="SKIP">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closedbconnection -->
      </class> <!-- TestCase_Repo.S1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
